project_id = "iogceaotdodvugrmogpp"

[functions.cartpanda-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.resend-welcome-sms]
verify_jwt = false

[functions.send-batch-emails]
verify_jwt = false
