project_id = "iogceaotdodvugrmogpp"

[functions.cartpanda-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.resend-welcome-sms]
verify_jwt = false

[functions.send-batch-emails]
verify_jwt = false

[functions.quiz-reengagement]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.hotmart-webhook]
verify_jwt = false

[functions.reminder-uncreated-accounts]
verify_jwt = false

[functions.send-family-invite]
verify_jwt = false
